"""
graph/state.py

Purpose
-------
Defines AgentState: the single shared state object that flows through
every node in the graph (orchestrator -> sql_deep_agent -> sql_query_tool
-> visualisation_subagent -> response_agent). LangGraph passes this dict
between nodes, and each node returns a partial update that gets merged
into it according to the reducers defined below.

Keeping all shared fields in one typed dict (rather than passing loose
arguments between functions) is what makes the graph inspectable and
checkpointable - the entire conversation/task state can be serialized,
saved, and resumed from any node.
"""

import operator
from typing import Annotated, Literal, Optional, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """Shared state passed between all nodes in the workflow graph.

    Fields
    ------
    messages: Full conversation history. The `add_messages` reducer
        appends new messages instead of overwriting the list, so each
        agent's output accumulates rather than replacing prior turns.
    user_query: The original natural-language question from the user.
    route: Orchestrator's routing decision - which path to take next.
    sql_query: The SQL statement generated by the SQL deep agent.
    sql_query_approved: Human-in-the-loop flag; True once a human has
        approved (or the query needed no approval).
    sql_result: Rows returned by executing sql_query, as a list of dicts.
    sql_deep_agent_iterations: How many plan->query->reflect loops the
        deep agent has taken, used to enforce SQL_DEEP_AGENT_MAX_ITERATIONS.
    sql_agent_finished: True once the deep agent has decided (or been
        forced by the iteration cap) to stop looping and hand off.
    sql_summary: The deep agent's plain-language summary of what the
        final sql_result shows, handed to the visualisation/response agents.
    needs_visualization: Orchestrator's decision on whether a chart is
        required for this query.
    chart_path: Filesystem path to the PNG chart produced by the
        visualisation subagent, if one was generated.
    chart_description: Short natural-language description of the chart,
        used by the response agent to reference it in prose.
    final_answer: The response agent's synthesized answer to the user.
    error: Any error message surfaced by a node, so downstream nodes and
        the human-in-the-loop reviewer can see what went wrong.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    user_query: str
    route: Optional[Literal["sql_only", "sql_and_visualization"]]
    sql_query: Optional[str]
    sql_query_approved: bool
    sql_result: Optional[list[dict]]
    sql_deep_agent_iterations: Annotated[int, operator.add]
    sql_agent_finished: bool
    sql_summary: Optional[str]
    needs_visualization: bool
    chart_path: Optional[str]
    chart_description: Optional[str]
    final_answer: Optional[str]
    error: Optional[str]


def initial_state(user_query: str) -> AgentState:
    """Build a fresh AgentState for a new user query.

    Called once by main.py / workflow.py when a run starts, so every
    field has a sane default and downstream nodes never hit a KeyError.
    """
    return AgentState(
        messages=[],
        user_query=user_query,
        route=None,
        sql_query=None,
        sql_query_approved=False,
        sql_result=None,
        sql_deep_agent_iterations=0,
        sql_agent_finished=False,
        sql_summary=None,
        needs_visualization=False,
        chart_path=None,
        chart_description=None,
        final_answer=None,
        error=None,
    )